site_name: 猫窝子站

theme:
  name: material
  palette:
  # 从mdn那里拿来的hhh
    # 浅色模式
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # 深色模式  
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - 首页: index.md
  - 关于猫窝: #我真服了，怎么这里还要加冒号
    - 历史: about/history.md
  - 帮助:
    - MkDocs使用指南: help/built-mkdocs.md
  - 猫窝维基百科:
    - 名人名言: wikis/setence.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: admonition
          class: admonition
          format: !!python/name:pymdownx.superfences.fence_div_format
